import type { Metadata } from "next";
import "./globals.scss";
import CustomFont from "next/font/local";
import Header from "./components/header/header.component";
import ReduxProvider from "./redux/provider";
import { Toaster } from "react-hot-toast";
const SFProText = CustomFont({
  src: [
    {
      path: "../../public/font/SF-Pro-Text-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/font/SF-Pro-Text-Semibold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/font/SF-Pro-Text-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-sfpro",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={SFProText.variable} suppressHydrationWarning>
        <Toaster></Toaster>
        <ReduxProvider>
          <Header></Header>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
